#!/bin/bash

# Compiler and linker flags
CXX="g++"
CXXFLAGS="-std=c++20 -Wall -Wextra -g" # -g for debugging
LDFLAGS="-L. -lraylib -framework Cocoa -framework OpenGL -framework IOKit -framework CoreAudio -framework CoreGraphics -shared"

# Source file and output executable
SRC_FILE="./rfb.cpp"
OUTPUT_EXEC="./dist/librfb.a"
cp ./rfb.hpp ./dist/rfb.hpp
echo "Compiling $SRC_FILE..."
$CXX $CXXFLAGS $SRC_FILE -o $OUTPUT_EXEC $LDFLAGS
g++ test.cpp -o test -L./dist -lrfb -std=c++20
if [ $? -eq 0 ]; then
    echo "Compilation successful. Running $OUTPUT_EXEC..."
    ./test
else
    echo "Compilation failed."
fi