#!/bin/bash



# This build script is deprecated, use cmakebob instead.


set -e
# Compiler and linker flags
CXX="g++"
CXXFLAGS="-std=c++20 -Wall -Wextra -g -Wmissing-field-initializers" # -g for debugging
LDFLAGS="-Llib -lraylib -framework Cocoa -framework OpenGL -framework IOKit -framework CoreAudio -framework CoreGraphics -shared -Wunused-parameter"

# Source file and output executable
SRC_FILE="./src/rfb.cpp"
OUTPUT_EXEC="./dist/librfb.a"
cp ./src/rfb.hpp ./dist/rfb.hpp
echo "Compiling $SRC_FILE..."
g++ -S $SRC_FILE -o rfb.s # im bored
$CXX $CXXFLAGS $SRC_FILE -o $OUTPUT_EXEC $LDFLAGS
g++ examples/test.cpp -o test -L./dist -lrfb -std=c++20 -Wunused-parameter
if [ $? -eq 0 ]; then
    echo "Compilation successful. Running $OUTPUT_EXEC..."
    ./test
else
    echo "Compilation failed."
fi